// <auto-generated />
using System;
using GeloraGorApp.Ef;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GeloraGorApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GeloraGorApp.Models.Jadwal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Catatan");

                    b.Property<int>("LapanganId");

                    b.Property<int>("PegawaiId");

                    b.Property<DateTime>("WaktuAkhir");

                    b.Property<DateTime>("WaktuAwal");

                    b.HasKey("Id");

                    b.HasIndex("LapanganId");

                    b.HasIndex("PegawaiId");

                    b.ToTable("Jadwal");
                });

            modelBuilder.Entity("GeloraGorApp.Models.JenisLapangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NamaJenis");

                    b.HasKey("Id");

                    b.ToTable("JenisLapangan");
                });

            modelBuilder.Entity("GeloraGorApp.Models.Lapangan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Catatan");

                    b.Property<string>("Foto");

                    b.Property<double>("Harga");

                    b.Property<int>("JenisId");

                    b.Property<string>("NamaLapangan");

                    b.HasKey("Id");

                    b.HasIndex("JenisId");

                    b.ToTable("Lapangan");
                });

            modelBuilder.Entity("GeloraGorApp.Models.Pegawai", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Alamat");

                    b.Property<string>("Email");

                    b.Property<string>("NamaPegawai");

                    b.Property<double>("NoTelp");

                    b.Property<string>("Password");

                    b.HasKey("Id");

                    b.ToTable("Pegawai");
                });

            modelBuilder.Entity("GeloraGorApp.Models.Jadwal", b =>
                {
                    b.HasOne("GeloraGorApp.Models.Lapangan", "Lapangan")
                        .WithMany("Jadwals")
                        .HasForeignKey("LapanganId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("GeloraGorApp.Models.Pegawai", "Pegawai")
                        .WithMany("Jadwals")
                        .HasForeignKey("PegawaiId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("GeloraGorApp.Models.Lapangan", b =>
                {
                    b.HasOne("GeloraGorApp.Models.JenisLapangan", "Jenis")
                        .WithMany("Lapangans")
                        .HasForeignKey("JenisId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
